name: p2cplus
favicon: null
layout_spectrum: 0.48935
typography_spectrum: 0.30184
title: P2C+ Conference
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98a6ef'
    - '#400bfd'
    - '#cd4dca'
    - '#eea640'
    - '#57f06a'
  brandStrength: 0.1875
  lightness: 0.3469922887161374
  saturation: 0.6836017919704318
  rhythmicContrast: 0.5
purpose: []
