typography_spectrum: 0.41251
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#848484'
    - '#3c3c3c'
    - '#0089ca'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7478
analytics:
  google: null
  facebook: null
  twitter: null
name: p2cplus
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: P2C+ Conference
description: Jesus Changes Everything
purpose: []
