name: p2cplus
favicon: null
layout_spectrum: 0.7478
typography_spectrum: 0.41251
title: P2C+ Conference
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#848484'
    - '#3c3c3c'
    - '#0089ca'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
